### ISSUE TITLE
get_time_step returns wrong value

### ISSUE THREAD

**Issue by astoeckel** [SpiNNakerManchester/sPyNNaker#147]
It is nice that the get_time_step method is implemented now. However executing

```
import pyNN.spiNNaker as sim

sim.setup(timestep=1.0)
print sim.get_time_step()
```

returns "1000.0", whereas the expected value is "1.0" (tested with pyNN.nest backend).

**Comment by alan-stokes** [comment]
fixed in the GFE prov after crash branch. Therefore will be merged into master and thus in the Another Fine Porduct From The Nonesnse Factory release at the end of this month,. therefore closing the issue

**Comment by apdavison** [comment]
Running in the HBP Collaboratory in March 2018 I still see this behaviour. Regression?

**Comment by rowleya** [comment]
I would guess so... I will investigate

**Comment by rowleya** [comment]
This looks like it has been broken when we added the PyNN 8 support.  I have reopened the issue so we will investigate

**Comment by andrewgait** [comment]
Closing again following merge.
